name: pull-request
on: pull_request

jobs:
  compile:
    name: 📦 DBT compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.9, 3.10]
    steps:
      - name: 🚧 Install OS dependencies
        run: sudo apt-get install libxml2-dev libxslt-dev

      - name: checkout
        uses: actions/checkout@v2

      - name: 🐍 Install python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: 🐍 Cache python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            ~/.cache
            !~/cache/exclude
          key: ${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('poetry.lock') }}

      - name: 🐍 Install Pip and Poetry
        run: pip install -U pip==21.2.4 poetry==1.1.9

      - name: 🐍 poetry install - Installing python dependencies
        run: poetry install --no-root --no-interaction
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: 🧪 pytest
        run: py.test --cov=amora --cov-report=term-missing --cov-report=xml

      - name: 🧪 SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: ${{ matrix.python == '3.10' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
